version: '3.8'

services:
  ffc-ahwr-eligibility:
    build:
      context: .
      target: production
    image: ffc-ahwr-eligibility
    container_name: ffc-ahwr-eligibility
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-eligibility-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      ELIGIBILITYRESPONSE_QUEUE_ADDRESS: ${ELIGIBILITYRESPONSE_QUEUE_ADDRESS:-ffc-ahwr-eligibility-response}${MESSAGE_QUEUE_SUFFIX}
      ELIGIBILITYREQUEST_QUEUE_ADDRESS: ${ELIGIBILITYREQUEST_QUEUE_ADDRESS:-ffc-ahwr-eligibility-request}${MESSAGE_QUEUE_SUFFIX}
