version: '3.8'

services:
  ffc-ahwr-eligibility:
    build:
      context: .
      target: production
    image: ffc-ahwr-eligibility
    container_name: ffc-ahwr-eligibility
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-eligibility-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
