version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-eligibility:
    build:
      target: development
    image: ffc-ahwr-eligibility-development
    container_name: ffc-ahwr-eligibility-development
    ports:
      - "3010:3000"
      - "9240:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
  ffc-ahwr-eligibility-postgres:
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
