version: '3.8'

services:
  ffc-ahwr-eligibility:
    build:
      context: .
      target: production
    image: ffc-ahwr-eligibility
    container_name: ffc-ahwr-eligibility
    depends_on:
      - ffc-ahwr-eligibility-postgres
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      DEBUG: sequelize*
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-eligibility-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      APPLY_SERVICE_URI: ${APPLY_SERVICE_URI:-http://localhost:3000/apply}
      EVENT_QUEUE_ADDRESS: ${EVENT_QUEUE_ADDRESS:-ffc-ahwr-event}${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY:-examplekey-644a2a30-7487-4e98-a908-b5ecd82d5225-644a2a30-7487-4e98-a908-b5ecd82d5225}
      NOTIFY_TEMPLATE_ID_WAITING_LIST: ${NOTIFY_TEMPLATE_ID_WAITING_LIST:-02912196-714b-4695-bb80-e977c0b77c1d}
      NOTIFY_TEMPLATE_ID_APPLY_INVITE_DEFRA_ID: ${NOTIFY_TEMPLATE_ID_APPLY_INVITE_DEFRA_ID:-edc864c7-1127-4a78-a1e6-516a27f9a0cc}
      POSTGRES_DB: ffc_ahwr_eligibility
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-ahwr-eligibility-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      REGISTER_YOUR_INTEREST_REQUEST_QUEUE_ADDRESS: ${REGISTER_YOUR_INTEREST_REQUEST_QUEUE_ADDRESS:-ffc-ahwr-register-your-interest-request}${MESSAGE_QUEUE_SUFFIX}
      WAITING_LIST_SCHEDULE: ${WAITING_LIST_SCHEDULE:-0 9 * * TUE}
      WAITING_LIST_SCHEDULER_ENABLED: ${WAITING_LIST_SCHEDULER_ENABLED:-true}
      WAITING_LIST_THRESHOLD_UPPER_LIMIT: ${WAITING_LIST_THRESHOLD_UPPER_LIMIT:-50}

  ffc-ahwr-eligibility-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_ahwr_eligibility
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
