environment: development
name: ffc-ahwr-eligibility
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-eligibility

labels: {}

appInsights:
  key:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-ahwr-eligibility-config-map

containerSecret:
  name: ffc-ahwr-eligibility-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  eligibilityRequestQueueAddress: ffc-ahwr-eligibility-request
  eligibilityResponseQueueAddress: ffc-ahwr-eligibility-response
  imagePullPolicy: IfNotPresent
  messageQueueHost: namespace.servicebus.windows.net
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000
  requestCpu: 10m
  requestMemory: 10Mi

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
