environment: development
name: ffc-ahwr-eligibility
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-eligibility

labels: {}

aadPodIdentity: true

appInsights:
  connectionString:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-ahwr-eligibility-config-map

containerSecret:
  name: ffc-ahwr-eligibility-container-secret
  type: Opaque

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: default
  replicas: 1
  restartPolicy: Always

container:
  registerYourInterestRequestQueueAddress: ffc-ahwr-register-your-interest-request
  notifyApiKey:
  notifyTemplateIdFarmerApplyInvite:
  notifyTemplateIdWaitingList:
  notifyTemplateIdGenericIneligible:
  emailTemplateIdIneligibleApplication:
  waitingListSchedule:
  waitingListSchedulerEnabled:
  waitingListThresholdUpperLimit:
  earlyAdoptionTeamEmailAddress:
  imagePullPolicy: IfNotPresent
  messageQueueHost: namespace.servicebus.windows.net
  limitMemory: 100Mi
  limitCpu: 80m
  port: 3000
  requestCpu: 40m
  requestMemory: 80Mi

postgresService:
  postgresDb: ffc_ahwr_eligibility
  postgresExternalName: namespace.postgres.database.azure.com
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

liquibase:
  contexts: prod

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
