environment: development
name: ffc-ahwr-eligibility
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-eligibility

labels: {}

aadPodIdentity: true

appInsights:
  key:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-ahwr-eligibility-config-map

containerSecret:
  name: ffc-ahwr-eligibility-container-secret
  type: Opaque

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 2
  priorityClassName: default
  replicas: 1
  restartPolicy: Always

container:
  registerYourInterestRequestQueueAddress: ffc-ahwr-register-your-interest-request
  imagePullPolicy: IfNotPresent
  messageQueueHost: namespace.servicebus.windows.net
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000
  requestCpu: 10m
  requestMemory: 10Mi

postgresService:
  postgresDb: ffc_ahwr_eligibility
  postgresExternalName: namespace.postgres.database.azure.com
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

liquibase:
  contexts: prod

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
