{{- include "ffc-helm-library.container-config-map" (list . "ffc-ahwr-eligibility.config-map") -}}
{{- define "ffc-ahwr-eligibility.config-map" -}}
data:
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  REGISTER_YOUR_INTEREST_REQUEST_QUEUE_ADDRESS: {{ quote .Values.container.registerYourInterestRequestQueueAddress }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresExternalName }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  DEBUG: sequelize*
  NOTIFY_EARLY_ADOPTION_TEAM_EMAIL_ADDRESS: {{ quote .Values.container.notifyEarlyAdoptionTeamEmailAddress }}
  NOTIFY_TEMPLATE_ID_WAITING_LIST_: {{ quote .Values.container.notifyTemplateIdWaitingList }}
  NOTIFY_TEMPLATE_ID_INELIGIBLE_GENERIC: {{ quote .Values.container.notifyTemplateIdGenericIneligible }}
  NOTIFY_TEMPLATE_ID_APPLY_INVITE: {{ quote .Values.container.notifyTemplateIdFarmerApplyInvite }}
  NOTIFY_TEMPLATE_ID_INELIGIBLE_APPLICATION: {{ quote .Values.container.notifyTemplateIdIneligibleApplication }}
  WAITING_LIST_SCHEDULE: {{ quote .Values.container.waitingListSchedule }}
  WAITING_LIST_SCHEDULER_ENABLED: {{ quote .Values.container.waitingListSchedulerEnabled }}
  WAITING_LIST_THRESHOLD_UPPER_LIMIT: {{ quote .Values.container.waitingListThresholdUpperLimit }}
  APPLY_SERVICE_URI: {{ quote .Values.container.applyServiceUri }}
{{- end -}}
