{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-eligibility.container-secret") -}}
{{- define "ffc-ahwr-eligibility.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  POSTGRES_USERNAME: {{ quote .Values.postgresService.postgresUser }}
  POSTGRES_PASSWORD: {{ quote .Values.postgresService.postgresPassword }}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
{{- end -}}
