{{- include "ffc-helm-library.deployment" (list . "ffc-ahwr-eligibility.deployment") -}}
{{- define "ffc-ahwr-eligibility.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-ahwr-eligibility.container") }}
{{- end -}}
