openapi: 3.0.3
info:
  title: Eligibility API
  description: |-
    Eligibility API for Animal Health and Welfare Review
  version: 0.1.0
tags:
  - name: waiting list
    description: Annual Health and Welfare Review waiting list
paths:
  /api/waiting-list:
    get:
      tags:
        - waiting-list
      summary: Check whether a farmer's or agents business email address is on the service waiting list.
      description: Check whether a farmer's or agents business email address is on the service waiting list
      operationId: waitingList
      parameters:
        - name: emailAddress
          in: query
          description: Farmer's business email address.
          required: true
          schema:
            type: string
            format: email
      responses:
        '200':
          description: The farmer's business email address is eligible.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaitingList'
        '400':
          description: Bad request. A valid email address must be specified.
        '5XX':
          description: Unexpected error.
components:
  schemas:
    WaitingList:
      type: object
      properties:
        alreadyRegistered:
          type: boolean
          example: true
        accessGranted:
          type: boolean
          example: true